/**
 * Employee API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Employee } from '../models/models';


import { Configuration }                                     from '../configuration';



export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create new employee
     * 
     * @param employee 
     */
    createEmployee(employee: Employee, extraHttpRequestParams?: any): Observable<Employee>;

    /**
     * Get all employees
     * 
     */
    getEmployees(extraHttpRequestParams?: any): Observable<Array<Employee>>;

}
