/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createEmployee } from '../fn/operations/create-employee';
import { CreateEmployee$Params } from '../fn/operations/create-employee';
import { Employee } from '../models/employee';
import { getEmployees } from '../fn/operations/get-employees';
import { GetEmployees$Params } from '../fn/operations/get-employees';

@Injectable({ providedIn: 'root' })
export class ApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getEmployees()` */
  static readonly GetEmployeesPath = '/employees';

  /**
   * Get all employees.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployees()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployees$Response(params?: GetEmployees$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Employee>>> {
    return getEmployees(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all employees.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployees$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployees(params?: GetEmployees$Params, context?: HttpContext): Observable<Array<Employee>> {
    return this.getEmployees$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Employee>>): Array<Employee> => r.body)
    );
  }

  /** Path part for operation `createEmployee()` */
  static readonly CreateEmployeePath = '/employees';

  /**
   * Create new employee.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createEmployee()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEmployee$Response(params: CreateEmployee$Params, context?: HttpContext): Observable<StrictHttpResponse<Employee>> {
    return createEmployee(this.http, this.rootUrl, params, context);
  }

  /**
   * Create new employee.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createEmployee$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEmployee(params: CreateEmployee$Params, context?: HttpContext): Observable<Employee> {
    return this.createEmployee$Response(params, context).pipe(
      map((r: StrictHttpResponse<Employee>): Employee => r.body)
    );
  }

}
